behaviors:
  RobotAgent:
    trainer_type: sac
    hyperparameters:
      learning_rate: 0.0003
      learning_rate_schedule: constant
      batch_size: 128
      buffer_size: 50000
      buffer_init_steps: 0
      tau: 0.005
      steps_per_update: 1.0
      save_replay_buffer: false
      init_entcoef: 1.0
      reward_signal_steps_per_update: 1.0
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
      goal_conditioning_type: hyper
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.95
        strength: 1.0
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
          goal_conditioning_type: hyper
          deterministic: false
    keep_checkpoints: 5
    checkpoint_interval: 500000
    max_steps: 50000
    time_horizon: 64
    summary_freq: 1000
    threaded: false
